apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DATABASE_PASSWORD: <DB_PWD>
  DATABASE_USER: airbyte
  DATABASE_PORT: "5432"
  DATABASE_HOST: <DB_HOST> # e.g. airbyte-eks.c4hvhyuxrcet.ap-south-1.rds.amazonaws.com

