apiVersion: v1
kind: Secret
metadata:
  name: airbyte-config-secrets
type: Opaque
stringData:
  # Enterprise License Key: user for enterprise deployment
  license-key: ## e.g. xxxxx.yyyyy.zzzzz

  # Database Secrets
  database-user: <database user>
  database-password: <database password>
  database-port: 5432
  database-host: <database host>
  DATABASE_PASSWORD: 
  DATABASE_USER: 

  # Instance Admin
  # instance-admin-email: ## e.g. admin@company.example
  # instance-admin-password: ## e.g. password

  # SSO OIDC Credentials
  # client-id: ## e.g. e83bbc57-1991-417f-8203-3affb47636cf
  # client-secret: ## e.g. wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  # s3 bucket creds
  S3_LOG_BUCKET: <s3 bucket name>
  S3_LOG_BUCKET_REGION: <s3 bucket region>
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY: 
  s3-access-key-id:
  s3-secret-access-key:

  AWS_KEY: 
  AWS_SECRET_KEY: 

  # AWS Secret Manager
  # aws-secret-manager-access-key-id: <AWS_KEY>
  # aws-secret-manager-secret-access-key: <AWS_SECRET_KEY>

  gcp.json: {
    "type":",
    "project_id": "",
    "private_key_id":",
    "private_key":",
    "client_email":",
    "client_id":",
    "auth_uri":",
    "token_uri":",
    "auth_provider_x509_cert_url":",
    "client_x509_cert_url":",
    "universe_domain":""
  }

