version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  superset:
    env_file:
      - superset.env
    image: "ddp-superset:0.1"
    networks:
      - app-network
    depends_on:
      - db
      - superset_cache
    command: >
      sh -c  "celery --app=superset.tasks.celery_app:app worker --pool=prefork -O fair -c 4 &&
              celery --app=superset.tasks.celery_app:app beat &&
              celery --app=superset.tasks.celery_app:app flower
              "

  db:
    image: postgres
    env_file:
      - db.env
    networks:
      - app-network

  superset_cache:
    image: redis
    networks:
      - app-network
