# Kubernetes API version
apiVersion: v1
# Resource type - creating a Service
kind: Service
metadata:
  # Name of the load balancer service - must be unique within the namespace
  name: airbyte-server-lb
  namespace: airbyte
  annotations:
    # Specifies that this should be an internal load balancer in AWS (updated annotation)
    # This means it won't be accessible from the internet, only within the VPC
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1800" # timeout of 30 minutes
    # Specify the load balancer type for better compatibility
    # service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  # Use AWS Load Balancer to expose the service
  type: LoadBalancer
  selector:
    # Target pods with these labels
    # These must match the labels on your Airbyte server pods
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/name: server
  ports:
    # Port mapping configuration
    - port: 80        # Port exposed by the load balancer
      targetPort: 8001  # Port that your Airbyte server is running on in the pods