apiVersion: v1
kind: Secret
metadata:
  name: superset-test-superset-env  ## superset-{{ Values.nameOverride }}-env
  namespace: superset
type: Opaque
stringData:
  # database
  DB_HOST: 
  DB_NAME: 
  DB_PASS: 
  DB_PORT: "5432"
  DB_USER: 
  SQLALCHEMY_DATABASE_URI:

  # app
  SUPERSET_SECRET_KEY: 

  # redis
  REDIS_CELERY_DB: "0"
  REDIS_DB: "1"
  REDIS_HOST: "superset-redis-headless" ## "{{ .Release.Name }}-redis-headless"
  REDIS_PORT: "6379"
  REDIS_PROTO: redis
  REDIS_USER: ""
