apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prom-stack-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: kube-prom-stack-pv
  storageClassName: gp2-prod