apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: monitoring-pvc
  storageClassName: gp2