apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: <vol-ID>
    fsType: ext4