apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  storageClassName: gp2
  accessModes:
    - ReadWriteMany # so that multiple pvc/services (their pods) can read/write to the same volume
  awsElasticBlockStore:
    volumeID: vol-0a2377b85a9597f54
    fsType: ext4